---
stopwatch:
  stopwatch:
    dayStatistic:
      default:
        expectedWorkTime: "6H40M"
        comment: "No comment"
  dates:
    amountOfDaysToShow: 600
    defaultFastEditButtonName: null
    fastEditButtons:
    - name: "Holiday"
      expected: "0S"
    - name: "Weekend"
      expected: "0S"
    - name: "Sick"
      expected: "0S"
    - name: "Workday"
      expected: "8H00M"
  devMode: false
  folderWithData: "<path-to-data>"
  defaultRecords:
  - "Daily"
  - "Task 1"
  - "Task 2"
  statistics:
    showWeekly: false
  report:
    numberOfDaysToShow: 2
    showTime: true
    groupBy: "REPORT"
    exportFormat: "JSON"
