name: Java CI with Gradle

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.4
          arguments: build
      - name: Upload build results
        uses: actions/upload-artifact@v4
        with:
          name: build-results
          path: desktop/build/os-specific-jars
      - name: Generate index.html for s3
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.4
          arguments: prepareIndexHtmlForS3
      - name: Upload index.html
        uses: actions/upload-artifact@v4
        with:
          name: index-html
          path: build/s3

  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download build results
        uses: actions/download-artifact@v4
        with:
          name: build-results
          path: desktop/build/os-specific-jars

      - name: Upload S3
        run: aws s3 cp desktop/build/os-specific-jars s3://${{ secrets.AWS_BUCKET }}/$FOLDER_NAME --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          FOLDER_NAME: ${{ github.ref_name }}

      - name: Download index.html
        uses: actions/download-artifact@v4
        with:
          name: index-html
          path: build/s3

      - name: Upload index.html to S3
        run: aws s3 cp build/s3/index.html s3://${{ secrets.AWS_BUCKET }}/index.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'